### ISSUE TITLE
Update `serde_json_path` to 0.6.0

### ISSUE THREAD

**Issue by hiltontj** [fdncred/nu_plugin_json_path#2]
Hey there, just thought I would drop an issue to update the version of [`serde_json_path`](https://docs.rs/serde_json_path/latest/serde_json_path/) to 0.6.0. Several fixes/improvements have gone in since the version currently used by this crate (0.3.1).

Notably,
* Several fixes to ensure compliance (see [compliance test suite](https://github.com/jsonpath-standard/jsonpath-compliance-test-suite))
* Function extensions supported in filters (`length`, `count`, `match`, `search`, `value`) as well as a new macro to define custom functions
* Improved API, via the `JsonPath` type, which allows for pre-compiled JSONPath queries - which may not be as relevant in your case
* More concise errors when parsing query strings

Check out the [change log](https://github.com/hiltontj/serde_json_path/blob/main/serde_json_path/CHANGELOG.md) in case you are interested.

**Comment by fdncred** [comment]
Thanks for the tip. I'll update this soon to support the latest version.

**Comment by fdncred** [comment]
I didn't realize this would be a major change and not a drop-in-replacement. Seems like things have changed significantly.

**Comment by hiltontj** [comment]
Yes there were several breaking changes in the API to move towards using the `JsonPath` type. If you'd like I can submit a PR.

**Comment by fdncred** [comment]
> Yes there were several breaking changes in the API to move towards using the `JsonPath` type. If you'd like I can submit a PR.

I think I have it sorted but if you have time to take a look to ensure it's correct, that would be appreciated.

**Comment by hiltontj** [comment]
> > Yes there were several breaking changes in the API to move towards using the `JsonPath` type. If you'd like I can submit a PR.
> 
> 
> 
> I think I have it sorted but if you have time to take a look to ensure it's correct, that would be appreciated.

It looks good!
